### ISSUE TITLE
pasting data into the search field

### ISSUE THREAD

**Issue by hobrien** [allendecid/TreeLink#1]
Hi. Thanks for a nice piece of software! I got so excited that I wrote a quick [blog post](https://heathobrien.wordpress.com/2016/01/04/phylogenetic-tree-browsers-treelink/) about it. As I mentioned in the post, it isn't possible to paste text into the search field, at least on my system (OSX 10.9.5). This is a bummer because pasting an accession number into the search field to locate it in the tree is a fairly common part of my workflow. Is this something that could easily be implemented or is it a limitation of the frameworks that you're using?

**Comment by allendecid** [comment]
Hey Heath, thanks for the blog post. Regrettably the platform we are using (node-webkit) for the desktop version has some problems with the clipboard of OSX. 

There is a quick fix for it by adding some code in the treelink.html file in the app folder.
You can open treelink.html with a code editor and add the following lines before the `</script>` tag.

```
var gui = require('nw.gui');
win = gui.Window.get();
var nativeMenuBar = new gui.Menu({ type: "menubar" });
try {
nativeMenuBar.createMacBuiltin("My App");
win.menu = nativeMenuBar;
} catch (ex) {
console.log(ex.message);
}
```

That should do it.
I'll add the fix in the next version. Thanks for the heads up.

**Comment by hobrien** [comment]
It works! Thanks
